name: Deploy personal website
description: |
  This workflow deploys a personal website using GitHub Actions. It includes a CodeQL security scan, builds the React application, and deploys it to GitHub Pages.
on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language to scan (e.g., javascript, python, etc.)'
        required: true
        default: 'javascript'

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  codeql-scan:
    uses: /malcolmdzimati/.github/workflows/security/codeql_security_scan_job.yml@main
    with:
      language: ${{ github.event.inputs.language }}

  build:
    uses: malcolmdzimati/workflow-templates/.github/workflows/build_publish/react/build_react_job.yml@main
    needs: codeql-scan # Ensures the build only runs if the CodeQL scan passes

  deploy:
    uses: malcolmdzimati/workflow-templates/.github/workflows/deploy/deploy_github_pages_job.yml@main
    needs: build # Ensures the deploy only runs if the build passes