name: Deploy personal website
description: |
  This workflow deploys a personal website using GitHub Actions. It includes a CodeQL security scan, builds the React application, and deploys it to GitHub Pages.
on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
      
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build_and_deploy:
    uses: /malcolmdzimati/.github/workflows/build_deploy_nextjs_x_github_pages.yml@main